Fix autotest output bug with rescoring experiments
Passing "None" for autotest_data caused a python exception. This patch
fixes the issue.

Traceback (most recent call last):
  File "./prio_test.py", line 45, in ?
    timeout=timeout)
  File "/export/hda3/teravest/blkcgroup_test_lib.py", line 819, in run_experiments
    autotest_data)
  File "/export/hda3/teravest/blkcgroup_test_lib.py", line 721, in run_single_experiment
    allowed_error, None)
  File "/export/hda3/teravest/blkcgroup_test_lib.py", line 359, in score_experiment
    autotest_data.append(('%d; %s; %s; %d; %d' %
AttributeError: 'NoneType' object has no attribute 'append'